# Generated by Django 5.0.4 on 2024-11-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('PHP', 'Philippine Peso'), ('JPY', 'Japanese Yen'), ('NONE', 'No Currency')], default='NONE', max_length=4),
        ),
    ]
