# Generated by Django 5.0.4 on 2025-01-05 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('bills', 'Bills'), ('debts', 'Debts'), ('food', 'Food'), ('grocery', 'Grocery'), ('medicine', 'Medicine'), ('savings', 'Savings'), ('others', 'Others')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bills', 'Bills'), ('food', 'Food'), ('grocery', 'Grocery'), ('medicine', 'Medicine'), ('savings', 'Savings'), ('others', 'Others')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
